apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: myapp
        image: abhishek2166/books-new:1403
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: books-secret
